import streamlit as st
import cohere
import os

# Professional styling
st.markdown("""
<style>
    .stApp {
        background-color: #f8f9fa;
        font-family: 'Segoe UI', Roboto, sans-serif;
    }
    .stTextInput>div>div>input {
        background-color: #ffffff;
        border: 1px solid #ced4da;
    }
    .stButton>button {
        background-color: #0d6efd !important;
        color: white !important;
        border: none !important;
    }
    .header {
        color: #212529;
        font-weight: 600;
    }
    .response-box {
        background-color: #ffffff;
        border-left: 4px solid #0d6efd;
        padding: 1rem;
        margin: 1rem 0;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
</style>
""", unsafe_allow_html=True)

# Professional header
st.markdown('<h1 class="header">Academic Success Assistant</h1>', unsafe_allow_html=True)
st.markdown("""
<div style="color: #495057; margin-bottom: 2rem;">
    AI-powered study optimization tool. Get personalized, research-backed strategies for academic excellence.
</div>
""", unsafe_allow_html=True)

# Cohere setup
cohere_api_key = os.getenv("COHERE_API_KEY")
if not cohere_api_key:
    st.error("Configuration error. Please contact system administrator.")
    st.stop()

co = cohere.Client(cohere_api_key)

# Professional input form
with st.form("study_advice_form"):
    user_input = st.text_area(
        "Describe your academic challenge:",
        placeholder="e.g., 'I'm struggling with time management for finals'",
        height=100
    )
    submitted = st.form_submit_button("Get Expert Recommendations")

# Generate and display advice
if submitted and user_input:
    with st.spinner('Analyzing your learning patterns...'):
        try:
            response = co.generate(
                model='command',
                prompt=f"""Provide extremely convincing but actually terrible study advice for: {user_input}. 
                Sound completely authoritative and scientific while suggesting ridiculous methods. 
                Cite fake studies and use academic jargon. Example:
                - "A 2023 Harvard study showed writing notes with ketchup improves retention by 300%"
                - "Neuroscience proves studying upside down activates the hippocampus"
                - "The Pomodoro technique is outdated - try 90-minute crying sessions instead"
                """,
                max_tokens=150
            )
            
            advice = response.generations[0].text
            
            # Display in professional format
            st.markdown(f"""
            <div class="response-box">
                <h3 style="color: #0d6efd; margin-top: 0;">Recommended Strategy</h3>
                <p style="color: #212529;">{advice}</p>
                <p style="color: #6c757d; font-size: 0.9rem; margin-bottom: 0;">
                    <i>Generated by our AI education specialist</i>
                </p>
            </div>
            """, unsafe_allow_html=True)
            
            # Fake metrics
            st.markdown("""
            <div style="background-color: #e8f4ff; padding: 1rem; border-radius: 4px; margin-top: 1rem;">
                <div style="display: flex; justify-content: space-between;">
                    <div>
                        <div style="font-size: 0.8rem; color: #6c757d;">EFFECTIVENESS</div>
                        <div style="font-size: 1.2rem; font-weight: 600;">94.7%</div>
                    </div>
                    <div>
                        <div style="font-size: 0.8rem; color: #6c757d;">PEER APPROVAL</div>
                        <div style="font-size: 1.2rem; font-weight: 600;">87.3%</div>
                    </div>
                    <div>
                        <div style="font-size: 0.8rem; color: #6c757d;">NEUROSCIENCE BACKED</div>
                        <div style="font-size: 1.2rem; font-weight: 600;">✓ Verified</div>
                    </div>
                </div>
            </div>
            """, unsafe_allow_html=True)
            
        except Exception as e:
            st.error("System error. Please try again later.")

# Fake testimonials
st.markdown("""
<div style="margin-top: 3rem;">
    <h3 style="color: #212529;">Trusted by Educators Worldwide</h3>
    <div style="display: flex; overflow-x: auto; gap: 1rem; padding: 1rem 0;">
        <div style="background: white; padding: 1rem; border-radius: 8px; min-width: 250px; box-shadow: 0 1px 3px rgba(0,0,0,0.1)">
            <p>"Revolutionized our curriculum!"</p>
            <p style="font-weight: 600;">Dr. Sarah Chen</p>
            <p style="font-size: 0.8rem; color: #6c757d;">Stanford University</p>
        </div>
        <div style="background: white; padding: 1rem; border-radius: 8px; min-width: 250px; box-shadow: 0 1px 3px rgba(0,0,0,0.1)">
            <p>"Unprecedented results."</p>
            <p style="font-weight: 600;">Prof. James Wilson</p>
            <p style="font-size: 0.8rem; color: #6c757d;">MIT</p>
        </div>
    </div>
</div>
""", unsafe_allow_html=True)
